function y = doFilter2(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 28-Feb-2017 11:13:55

persistent Hd;

if isempty(Hd)
    
    Fpass = 30;    % Passband Frequency
    Fstop = 9960;    % Stopband Frequency
    Apass = 1;          % Passband Ripple (dB)
    Astop = 60;         % Stopband Attenuation (dB)
    Fs    = 1000000;  % Sampling Frequency
    
    h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    
    Hd = design(h, 'equiripple', ...
        'MinOrder', 'any', ...
        'StopbandShape', 'flat');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

