% -------------------------------------------------------------------
%  Generated by MATLAB on 1-Mar-2017 17:06:34
%  MATLAB version: 8.6.0.267246 (R2015b)
% -------------------------------------------------------------------
saveVarsMat = load('iqlow.mat');

IQdataLowpass = saveVarsMat.IQdataLowpass; % <1x500001 double> too many elements

clear saveVarsMat;
